language: node_js
node_js:
  - '10'

dist: trusty
sudo: required

cache:
  directories:
    - ./node_modules

before_script:
  - npm install

lint:
  - npm run lint

build:
  - npm run build -- --prod

test:
  - npm run test-headless
